# Generated by Django 3.1.2 on 2020-11-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietitianProfile',
            fields=[
                ('First_name', models.CharField(max_length=15)),
                ('Last_name', models.CharField(max_length=15)),
                ('Phone_number', models.IntegerField()),
                ('Country', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=25, primary_key=True, serialize=False)),
                ('Is_approved', models.BooleanField(default=False, editable=False)),
                ('Status', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeLocation',
            fields=[
                ('Location_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Latitude', models.CharField(max_length=10)),
                ('Longitude', models.CharField(max_length=10)),
                ('Phone_number', models.IntegerField()),
                ('Street', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=25)),
                ('Country', models.CharField(max_length=25)),
                ('Is_approved', models.BooleanField(default=False, editable=False)),
                ('Status', models.BooleanField(default=False, editable=False)),
                ('User_name', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Dietitian.dietitianprofile')),
            ],
        ),
    ]
