# Generated by Django 3.1.2 on 2020-11-05 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dietitian', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietitianprofile',
            name='Is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dietitianprofile',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practicelocation',
            name='Is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practicelocation',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='practicelocation',
            name='User_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dietitian.dietitianprofile'),
        ),
    ]
